
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabila AAP
 */
public class Frame2 extends javax.swing.JFrame {
 String str, str1, str2, nomor=""; 
 int choice,z,pin=1324,counter=0,a=3;
 int pilih,t,s,d,p,tab=50000;

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Penyetoran = new javax.swing.JButton();
        Bantuan = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        Penarikan = new javax.swing.JButton();
        ISaldo = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Penyetoran.setBackground(new java.awt.Color(204, 204, 204));
        Penyetoran.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Penyetoran.setText("<");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(Penyetoran);
        Penyetoran.setBounds(30, 100, 90, 60);

        Bantuan.setBackground(new java.awt.Color(204, 204, 204));
        Bantuan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Bantuan.setText("<");
        getContentPane().add(Bantuan);
        Bantuan.setBounds(30, 230, 90, 60);

        bExit.setBackground(new java.awt.Color(204, 204, 204));
        bExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bExit.setText("<");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit);
        bExit.setBounds(30, 360, 90, 60);

        Penarikan.setBackground(new java.awt.Color(204, 204, 204));
        Penarikan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Penarikan.setText(">");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        getContentPane().add(Penarikan);
        Penarikan.setBounds(650, 360, 90, 60);

        ISaldo.setBackground(new java.awt.Color(204, 204, 204));
        ISaldo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ISaldo.setText(">");
        ISaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISaldoActionPerformed(evt);
            }
        });
        getContentPane().add(ISaldo);
        ISaldo.setBounds(650, 100, 90, 60);

        Transfer.setBackground(new java.awt.Color(204, 204, 204));
        Transfer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Transfer.setText(">");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(650, 230, 90, 60);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penarikan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 380, 140, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAKUKAN TRANSAKSI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 30, 300, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penyetoran");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bantuan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 250, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Exit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 380, 140, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informasi Saldo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 120, 200, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transfer");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 250, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 0, 490, 480);

        setSize(new java.awt.Dimension(786, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        new TerimaKasih().show();
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung
        s = Integer.parseInt(str1);
        setor hasil = new setor();
        hasil.menabung(tab, s);
        tab =hasil.getsaldo(); 
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void ISaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISaldoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab);
    }//GEN-LAST:event_ISaldoActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transaksi: " ); //menabung
        d = Integer.parseInt(str1);
        transaksi kirim = new transaksi();
        kirim.mengirim(tab, d);
        tab =kirim.getsaldo(); 
        
    }//GEN-LAST:event_TransferActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        // TODO add your handling code here:
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
        t = Integer.parseInt(str1);
        tarik mengambil = new tarik();
        mengambil.ambil(tab,t);
        tab =mengambil.getsaldo();
    }//GEN-LAST:event_PenarikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton ISaldo;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton Penyetoran;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton bExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
